name = "code_c"
display = "C (code)"
words = [
  "#include", "<stdio.h>", "<stdlib.h>", "<string.h>", "<stdint.h>", "<stdbool.h>",
  "<assert.h>", "int", "main(void)", "char", "return", "0;", "printf()", "scanf()",
  "fprintf()", "stderr", "stdout", "stdin", "malloc()", "calloc()", "realloc()",
  "free()", "memcpy()", "memset()", "strlen()", "strcpy()", "strcmp()", "strncpy()",
  "sizeof()", "void", "short", "long", "float", "double", "unsigned", "signed",
  "const", "static", "extern", "volatile", "register", "struct", "union", "enum",
  "typedef", "if", "else", "for", "while", "do", "switch", "case", "default:",
  "break;", "continue;", "goto", "NULL", "EOF", "size_t", "uint8_t", "uint32_t",
  "int64_t", "bool", "true", "false", "FILE", "fopen()", "fclose()", "fgets()",
  "fputs()", "fread()", "fwrite()", "#define", "#ifndef", "#ifdef", "#endif",
  "#pragma", "#if", "#else", "inline", "restrict", "*ptr", "&x", "ptr->next", "->",
  "++", "--", "!=", "==", "<=", ">=", "&&", "||", "<<", ">>", "%d", "%s", "%zu", "\\n",
  "exit()", "abort()", "atoi()", "i", "=", "<", "n;", "buf[256];", "node", "*next;",
  "Node;"
]
