name = "code_zig"
display = "Zig (code)"
words = [
  "const", "var", "fn", "pub", "return", "if", "else", "while", "for", "switch",
  "break", "continue", "defer", "errdefer", "try", "catch", "orelse", "unreachable",
  "struct", "enum", "union", "error", "opaque", "comptime", "inline", "noinline",
  "export", "extern", "test", "and", "or", "null", "undefined", "true", "false",
  "packed", "align", "allowzero", "volatile", "noalias", "threadlocal", "callconv",
  "linksection", "anyframe", "suspend", "resume", "nosuspend", "asm", "u8", "u16",
  "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64", "isize", "f16", "f32",
  "f64", "f128", "bool", "void", "anyerror", "anytype", "anyopaque", "type",
  "noreturn", "comptime_int", "comptime_float", "c_int", "[]u8", "[]const", "[]T",
  "[*]u8", "[4]u8", "[_]u8", "?*T", "?T", "!void", "*const", "*T", "*Self",
  "anyerror!void", "@import(\"std\")", "@import(\"std\");", "@import(\"builtin\")",
  "@intCast()", "@as()", "@sizeOf()", "@TypeOf()", "@This()", "@field()", "@ptrCast()",
  "@floatFromInt()", "@intFromFloat()", "@intFromEnum()", "@enumFromInt()",
  "@truncate()", "@min()", "@max()", "@memcpy()", "@memset()", "@panic()",
  "@compileError()", "@embedFile()", "@hasDecl()", "@typeInfo()", "@tagName()",
  "@errorName()", "@divTrunc()", "@mod()", "@rem()", "@bitCast()", "@alignOf()",
  "@src()", "@Vector()", "@splat()", "@abs()", "@sqrt()", "std", "std.debug.print()",
  "std.debug.assert()", "std.mem.Allocator", "std.mem.eql()", "std.mem.indexOf()",
  "std.mem.splitScalar()", "std.mem.tokenizeScalar()", "std.mem.sort()",
  "std.fmt.allocPrint()", "std.fmt.bufPrint()", "std.fmt.parseInt()", "std.ArrayList",
  "std.StringHashMap", "std.AutoHashMap", "std.heap.page_allocator",
  "std.heap.GeneralPurposeAllocator", "std.heap.ArenaAllocator",
  "std.testing.allocator", "std.testing.expect()", "std.testing.expectEqual()",
  "std.fs.cwd()", "std.process.argsAlloc()", "std.process.exit()", "std.log.info()",
  "std.log.err()", "std.math.maxInt()", "std.time.milliTimestamp()", "std.Thread",
  "std.meta", "std.json", "std.ascii", "allocator", "allocator.alloc()",
  "allocator.free()", "allocator.create()", "allocator.destroy()", "allocator.dupe()",
  "list.deinit()", "list.append()", "list.items", "map.put()", "map.get()",
  "gpa.allocator()", "arena.deinit()", ".deinit()", ".init()", ".items", ".len",
  ".ptr", ".{}", ".?", ".*", "x.*", "&x", "=>", "|x|", "|*x|", "|i|", "|err|", "...",
  "..", "++", "**", "+%", "-%", "*%", "<<", ">>", "==", "!=", "Self", "self", "main()",
  "zig", "build", "build.zig", "build.zig.zon"
]
