name = "code_elixir"
display = "Elixir (code)"
words = [
  "defmodule", "def", "defp", "defmacro", "defstruct", "defimpl", "defprotocol",
  "defdelegate", "defguard", "defexception", "do", "end", "fn", "->", "case", "cond",
  "with", "if", "else", "unless", "when", "receive", "after", "try", "rescue", "catch",
  "raise", "reraise", "throw", "for", "in", "import", "alias", "require", "use",
  "quote", "unquote", "true", "false", "nil", "and", "or", "not", "do:", "else:",
  ":ok", ":error", ":noreply", ":reply", ":stop", "@moduledoc", "@doc", "@spec",
  "@impl", "@type", "@typedoc", "@behaviour", "@callback", "@derive", "@enforce_keys",
  "@tag", "|>", "<-", "=>", "++", "--", "<>", "=~", "&", "&1", "&2", "%{}", "[]", "{}",
  "::", "..", "|", "\\\\", "^x", "_", "\"#{x}\"", "~r//", "~s()", "~w()",
  "~D[2024-01-01]", "%User{}", "%__MODULE__{}", "__MODULE__", "[h|t]", "[head|tail]",
  "&Enum.map/2", "&IO.puts/1", "Enum.map", "Enum.filter", "Enum.reduce", "Enum.each",
  "Enum.count", "Enum.sum", "Enum.sort", "Enum.sort_by", "Enum.find", "Enum.any?",
  "Enum.all?", "Enum.member?", "Enum.into", "Enum.join", "Enum.group_by",
  "Enum.with_index", "Enum.zip", "Enum.take", "Enum.uniq", "Enum.flat_map",
  "Enum.reverse", "Enum.at", "Enum.max", "Enum.min", "Enum.chunk_every", "Enum.reject",
  "Enum.map_join", "Map.get", "Map.put", "Map.merge", "Map.fetch", "Map.fetch!",
  "Map.delete", "Map.keys", "Map.values", "Map.new", "Map.update", "Map.has_key?",
  "List.first", "List.last", "List.flatten", "List.wrap", "String.split",
  "String.trim", "String.length", "String.upcase", "String.downcase",
  "String.to_integer", "String.contains?", "String.replace", "String.starts_with?",
  "Integer.to_string", "Integer.parse", "Keyword.get", "Stream.map", "Stream.filter",
  "IO.puts", "IO.inspect", "IO.gets", "Kernel", "spawn", "spawn_link", "send",
  "self()", "Process.sleep", "Process.send_after", "GenServer", "GenServer.start_link",
  "GenServer.call", "GenServer.cast", "handle_call", "handle_cast", "handle_info",
  "init", "start_link", "Agent", "Agent.start_link", "Agent.get", "Task", "Task.async",
  "Task.await", "Supervisor", "Supervisor.start_link", "Registry", "Application",
  "Logger", "Logger.info", "Logger.error", "File.read!", "File.write!", "Path.join",
  "Jason.encode!", "Jason.decode!", "is_nil", "is_binary", "is_integer", "is_list",
  "is_map", "elem", "hd", "tl", "length", "to_string", "inspect", "put_elem", "apply",
  "Ecto", "Ecto.Changeset", "Repo.all", "Repo.get", "Repo.insert", "cast",
  "validate_required", "Phoenix", "conn", "plug", "render", "json", "mix", "mix.exs",
  "iex", "ExUnit.Case", "test", "assert", "refute", "describe", "setup", "doctest"
]
