name = "code_lua"
display = "Lua (code)"
words = [
  "local", "function", "return", "end", "if", "then", "elseif", "else", "for", "in",
  "do", "while", "repeat", "until", "break", "goto", "and", "or", "not", "nil", "true",
  "false", "self", "require", "print()", "pairs()", "ipairs()", "type()", "tostring()",
  "tonumber()", "pcall()", "xpcall()", "error()", "assert()", "select()", "next()",
  "setmetatable()", "getmetatable()", "rawget()", "rawset()", "rawequal()", "rawlen()",
  "unpack()", "load()", "loadfile()", "dofile()", "collectgarbage()",
  "coroutine.create()", "coroutine.resume()", "coroutine.yield()", "coroutine.wrap()",
  "coroutine.status()", "string.format()", "string.sub()", "string.find()",
  "string.gsub()", "string.gmatch()", "string.match()", "string.len()", "string.rep()",
  "string.byte()", "string.char()", "string.lower()", "string.upper()",
  "string.reverse()", "s:sub()", "s:find()", "s:gsub()", "s:match()", "s:gmatch()",
  "s:upper()", "s:lower()", "s:len()", "table.insert()", "table.remove()",
  "table.concat()", "table.sort()", "table.pack()", "table.unpack()", "math.floor()",
  "math.ceil()", "math.max()", "math.min()", "math.abs()", "math.sqrt()",
  "math.random()", "math.randomseed()", "math.huge", "math.pi", "math.fmod()",
  "math.tointeger()", "os.time()", "os.clock()", "os.date()", "os.getenv()",
  "os.exit()", "os.remove()", "os.rename()", "io.write()", "io.read()", "io.open()",
  "io.lines()", "io.stdout", "f:read()", "f:write()", "f:close()", "f:lines()",
  "utf8.char()", "utf8.len()", "package.path", "package.loaded", "_G", "_ENV",
  "_VERSION", "arg", "..", "~=", "==", "<=", ">=", "<", ">", "=", "#", "{}", "[]", ":",
  "...", "--", "#t", "#list", "t[#t+1]", "t[i]", "t.x", "k", "v", "i", "M", "M.new()",
  "self.x", "obj:method()", "{...}", "__index", "__newindex", "__call", "__tostring",
  "__eq", "__lt", "__le", "__add", "__concat", "__len", "__gc", "__mode",
  "__metatable", "love.load()", "love.update(dt)", "love.draw()", "love.keypressed()",
  "love.graphics.print()", "love.graphics.rectangle()", "dt", "vim.api", "vim.opt",
  "vim.g", "vim.o", "vim.fn", "vim.cmd()", "vim.keymap.set()", "vim.notify()",
  "vim.api.nvim_create_autocmd()", "vim.api.nvim_set_keymap()",
  "vim.tbl_deep_extend()"
]
