name = "code_ocaml"
display = "OCaml (code)"
words = [
  "let", "in", "rec", "and", "fun", "function", "match", "with", "if", "then", "else",
  "begin", "end", "type", "of", "module", "struct", "sig", "open", "include",
  "functor", "val", "mutable", "ref", "when", "as", "try", "raise", "exception",
  "assert", "lazy", "method", "object", "class", "inherit", "new", "private",
  "virtual", "external", "constraint", "for", "to", "downto", "while", "do", "done",
  "nonrec", "land", "lor", "lxor", "lsl", "lsr", "asr", "mod", "true", "false", "()",
  "unit", "int", "float", "string", "bool", "char", "list", "array", "option", "exn",
  "bytes", "int64", "'a", "'b", "Some", "None", "Ok", "Error", "Not_found",
  "Invalid_argument", "Failure", "Exit", "List.map", "List.iter", "List.iteri",
  "List.mapi", "List.fold_left", "List.fold_right", "List.filter", "List.filter_map",
  "List.length", "List.rev", "List.nth", "List.hd", "List.tl", "List.mem",
  "List.assoc", "List.find", "List.find_opt", "List.exists", "List.for_all",
  "List.sort", "List.sort_uniq", "List.concat", "List.init", "List.combine",
  "List.split", "List.append", "List.flatten", "Array.make", "Array.length",
  "Array.get", "Array.set", "Array.init", "Array.map", "Array.iter", "Array.of_list",
  "Array.to_list", "String.length", "String.concat", "String.sub", "String.get",
  "String.split_on_char", "String.trim", "String.uppercase_ascii", "String.equal",
  "String.make", "Printf.printf", "Printf.sprintf", "Printf.eprintf", "Format.printf",
  "Format.fprintf", "print_endline", "print_string", "print_int", "print_newline",
  "read_line", "string_of_int", "int_of_string", "float_of_int", "int_of_float",
  "string_of_float", "Hashtbl.create", "Hashtbl.add", "Hashtbl.replace",
  "Hashtbl.find", "Hashtbl.find_opt", "Hashtbl.mem", "Hashtbl.iter", "Hashtbl.remove",
  "Option.map", "Option.value", "Option.get", "Option.is_some", "Result.map",
  "Result.bind", "Map.Make", "Set.Make", "Buffer.create", "Buffer.add_string",
  "Buffer.contents", "Seq", "Fun.id", "Stdlib", "compare", "failwith", "invalid_arg",
  "ignore", "fst", "snd", "not", "exit", "incr", "decr", "min", "max", "abs", "succ",
  "pred", "::", "@", "^", ";", ";;", "<>", "=", "==", "!=", "<", ">", "<=", ">=", "+",
  "-", "*", "/", "+.", "*.", "/.", "-.", "|>", "@@", ":=", "!", "->", "|", "_", "[]",
  "[||]", "~f", "~init", "x::xs", "acc", "xs", "let*", "let+", ">>=", ">|=",
  "[@@inline]", "Lwt", "Lwt.return", "Core", "ppx_deriving", "dune", "opam", "utop",
  ".ml", ".mli"
]
